steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/gradguru', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/gradguru']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'gradguru',
      '--image', 'gcr.io/$PROJECT_ID/gradguru',
      '--platform', 'managed',
      '--region', 'europe-west2',
      '--allow-unauthenticated'
    ]

images:
  - 'gcr.io/$PROJECT_ID/gradguru'
